ALTER TABLE `T_WLT_CHARGE_L` DROP CHECK `CK_WLT_CHARGE_L_STATUS`;

ALTER TABLE `T_WLT_CHARGE_L` ADD CONSTRAINT `CK_WLT_CHARGE_L_STATUS`
    CHECK (`status` IN ('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED'));