-- 자녀가 승인 대기(PENDING) 중인 가입 신청을 스스로 취소할 수 있도록 CANCELED 상태를 추가한다.
-- 예/적금 상태 제약은 스키마 파일 기준 5개 값이고, 대출은 V021에서 DEFAULTED가 추가된 6개 값이 현재 상태다.
ALTER TABLE `T_DPT_ENROLL_M`
    DROP CHECK `CK_DPT_ENROLL_M_STATUS`;
ALTER TABLE `T_DPT_ENROLL_M`
    ADD CONSTRAINT `CK_DPT_ENROLL_M_STATUS`
    CHECK (`status` IN ('PENDING', 'REJECTED', 'CANCELED', 'ACTIVE', 'MATURED', 'TERMINATED'));

ALTER TABLE `T_SVG_ENROLL_M`
    DROP CHECK `CK_SVG_ENROLL_M_STATUS`;
ALTER TABLE `T_SVG_ENROLL_M`
    ADD CONSTRAINT `CK_SVG_ENROLL_M_STATUS`
    CHECK (`status` IN ('PENDING', 'REJECTED', 'CANCELED', 'ACTIVE', 'MATURED', 'TERMINATED'));

ALTER TABLE `T_LON_ENROLL_M`
    DROP CHECK `CK_LON_ENROLL_M_STATUS`;
ALTER TABLE `T_LON_ENROLL_M`
    ADD CONSTRAINT `CK_LON_ENROLL_M_STATUS`
    CHECK (`status` IN ('PENDING', 'REJECTED', 'CANCELED', 'ACTIVE', 'OVERDUE', 'DEFAULTED', 'REPAID'));
