-- 알림(T_NTF_NOTI_L)의 딥링크 대상 유형에 카테고리 정책 변경을 추가한다.
-- 기존 CHECK 제약조건은 V027에서 정의한 16개 값만 허용하므로 먼저 제거한 뒤 다시 만든다.
ALTER TABLE `T_NTF_NOTI_L`
    DROP CHECK `CK_NTF_NOTI_L_REFERENCE_TYPE`;

ALTER TABLE `T_NTF_NOTI_L`
    ADD CONSTRAINT `CK_NTF_NOTI_L_REFERENCE_TYPE`
    CHECK (`reference_type` IS NULL OR `reference_type` IN (
        'QUEST', 'TODAY_PERMISSION', 'CONNECTION', 'TRANSFER', 'PAYMENT',
        'CHARGE', 'DEPOSIT_ENROLLMENT', 'SAVING_ENROLLMENT', 'LOAN_ENROLLMENT',
        'DEPOSIT_MATURITY', 'SAVING_MATURITY', 'SAVING_PAYMENT', 'LOAN_REPAYMENT',
        'DEPOSIT_TERMINATION', 'SAVING_TERMINATION', 'TEENY_SCORE_GRADE',
        'CATEGORY_POLICY'
    ));

ALTER TABLE `T_NTF_NOTI_L`
    MODIFY COLUMN `reference_type` VARCHAR(50) NULL
        COMMENT '딥링크 대상 테이블: QUEST/TODAY_PERMISSION/CONNECTION/TRANSFER/PAYMENT/CHARGE/DEPOSIT_ENROLLMENT/SAVING_ENROLLMENT/LOAN_ENROLLMENT/DEPOSIT_MATURITY/SAVING_MATURITY/SAVING_PAYMENT/LOAN_REPAYMENT/DEPOSIT_TERMINATION/SAVING_TERMINATION/TEENY_SCORE_GRADE/CATEGORY_POLICY (CHECK)';
