-- ============================================================
-- 가족 핀테크 서비스 스키마 (INDEX / UNIQUE / CHECK 반영본)
-- CREATE TABLE은 원본 구조 유지, 제약조건은 ALTER TABLE로 추가
-- ============================================================

CREATE TABLE `T_PAY_METHOD_M` (
	`id`	BIGINT	NOT NULL	COMMENT '결제수단 아이디',
	`parent_id`	BIGINT	NOT NULL	COMMENT '소유 부모 회원 (FK member) (INDEX)',
	`billing_key`	VARCHAR(255)	NOT NULL	COMMENT '토스 빌링키 (자동충전용, 암호화 저장)',
	`type`	VARCHAR(20)	NOT NULL	COMMENT '거래수단 유형: CARD(카드), ACCOUNT(계좌) (CHECK)',
	`card_company`	VARCHAR(50)	NULL	COMMENT '표시용 카드사명 (type이 CARD면 not null CHECK)',
	`masked_card_number`	VARCHAR(50)	NULL	COMMENT '표시용 마스킹 카드번호 (type이 CARD면 not null CHECK)',
	`account_bank_name`	VARCHAR(50)	NULL	COMMENT '계좌 은행명 (type이 ACCOUNT면 not null CHECK)',
	`account_number`	VARCHAR(50)	NULL	COMMENT '계좌번호 (마스킹) (type이 ACCOUNT면 not null CHECK)',
	`is_primary`	BOOLEAN	NOT NULL	DEFAULT FALSE	COMMENT '주거래 수단 여부 (자동충전에 사용)',
	`status`	VARCHAR(20)	NOT NULL	DEFAULT 'ACTIVE'	COMMENT '상태: ACTIVE / INACTIVE / EXPIRED (CHECK)',
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록 일시',
	`updated_at`	DATETIME	NULL	COMMENT '수정 일시'
);

CREATE TABLE `T_WLT_TRF_L` (
	`id`	BIGINT	NOT NULL	COMMENT '송금 아이디 (용돈, 예적금, 대출, 이자 등)',
	`from_wallet_id`	BIGINT	NOT NULL	COMMENT '송금 지갑 (FK wallet) (INDEX)',
	`to_wallet_id`	BIGINT	NOT NULL	COMMENT '입금 지갑 (FK wallet) (INDEX)',
	`idempotency_key`	CHAR(36)	NOT NULL	COMMENT '멱등성 키 (UUID) (UNIQUE)',
	`amount`	BIGINT	NOT NULL	COMMENT '송금 금액 (양수인지 CHECK)',
	`type`	VARCHAR(50)	NOT NULL	COMMENT '유형: ALLOWANCE(용돈) / DEPOSIT(예금) / SAVING(적금) / LOAN(대출) / TRANSFER(일반송금) (CHECK)',
	`status`	VARCHAR(20)	NOT NULL	DEFAULT 'PENDING'	COMMENT '상태: PENDING(대기) / CHARGING(충전 대기) / COMPLETED( 완료) / FAILED(실패) / CANCELLED(취소) (CHECK)',
	`failure_reason`	VARCHAR(30)	NULL	COMMENT '실패 사유 코드',
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '시도 일시',
	`updated_at`	DATETIME	NULL	COMMENT '상태 변경 일시'
);

CREATE TABLE `T_MCC_POLICY_M` (
	`id`	BIGINT	NOT NULL	COMMENT '자녀별 커스텀 정책 아이디',
	`parent_id`	BIGINT	NOT NULL	COMMENT '설정한 부모 (FK member) (INDEX)',
	`child_id`	BIGINT	NOT NULL	COMMENT '대상 자녀 (FK member, 자녀+카테고리 UNIQUE)',
	`merchant_category_id`	BIGINT	NOT NULL	COMMENT '대상 업종 (FK category)',
	`policy`	VARCHAR(20)	NOT NULL	COMMENT '커스텀 정책: ALLOW/WATCH/BLOCK. 이 행이 없으면 category.default_policy 적용 (CHECK)',
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '생성 일시',
	`updated_at`	DATETIME	NULL	COMMENT '수정 일시'
);

CREATE TABLE `T_TDP_REQ_L` (
	`id`	BIGINT	NOT NULL	COMMENT '오늘만 허용 요청 아이디',
	`parent_id`	BIGINT	NOT NULL	COMMENT '요청 받은 부모 (FK member) (INDEX)',
	`child_id`	BIGINT	NOT NULL	COMMENT '요청한 자녀 (FK member) (INDEX)',
	`reason`	VARCHAR(255)	NULL	COMMENT '자녀가 작성한 요청 사유',
	`status`	VARCHAR(20)	NOT NULL	DEFAULT 'PENDING'	COMMENT '상태: PENDING(대기)/APPROVED(승인)/REJECTED(거절)/EXPIRED(만료) (CHECK)',
	`expired_at`	DATETIME	NOT NULL	COMMENT '허용 만료 일시 (당일 자정, 서버 계산)',
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '요청 생성 일시',
	`updated_at`	DATETIME	NULL	COMMENT '수정 일시',
	`reviewed_at`	DATETIME	NULL	COMMENT '부모 검토 일시'
);

CREATE TABLE `T_LON_REPAYHIST_H` (
	`id`	BIGINT	NOT NULL	COMMENT '대출 상환 이력 시퀀스',
	`loan_enrollment_id`	BIGINT	NOT NULL	COMMENT '대출 가입 정보 아이디 (INDEX)',
	`transfer_id`	BIGINT	NULL	COMMENT '송금 시도 아이디 (UNIQUE)',
	`installment_no`	SMALLINT	NOT NULL	COMMENT '상환 회차',
	`principal_amount`	BIGINT	NOT NULL	COMMENT '상환 원금 (0 이상인지 CHECK)',
	`paid_principal_amount`	BIGINT	NOT NULL	COMMENT '실제로 상환한 금액 (0 이상인지 CHECK)',
	`interest_amount`	BIGINT	NOT NULL	COMMENT '이번 회차 이자 (실시간 신뢰도 점수 반영 X) (0 이상인지 CHECK)',
	`paid_interest_amount`	BIGINT	NOT NULL	COMMENT '실제로 낸 이자 금액 (0 이상인지 CHECK)',
	`status`	VARCHAR(10)	NOT NULL	COMMENT 'PAID(상환완료)/OVERDUE(연체)/PARTIAL(부분상환) (CHECK)',
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '생성 일시',
	`overdue_start_at`	DATETIME	NULL	COMMENT '연체 시작 일시 (연체이자는 납부시점 실시간 계산)',
	`paid_at`	DATETIME	NULL	COMMENT '실제 상환 일시'
);

CREATE TABLE `T_PAY_TRAN_L` (
	`id`	BIGINT	NOT NULL	COMMENT '결제 아이디',
	`wallet_id`	BIGINT	NOT NULL	COMMENT '결제한 지갑 (FK wallet) (INDEX)',
	`original_payment_id`	BIGINT	NULL	COMMENT '취소 시 원결제 참조 아이디',
	`category_id`	BIGINT	NULL	COMMENT '판정 업종 스냅샷 (FK category, 자녀 QR결제만)',
	`idempotency_key`	CHAR(36)	NOT NULL	COMMENT '멱등성 키 (UUID) (UNIQUE)',
	`applied_policy`	VARCHAR(20)	NULL	COMMENT '적용 정책 스냅샷: ALLOW / WATCH / BLOCK (CHECK)',
	`amount`	BIGINT	NOT NULL	COMMENT '시도 금액 (양수인지 CHECK)',
	`status`	VARCHAR(10)	NOT NULL	DEFAULT 'PENDING'	COMMENT '결과: PENDING(토스 승인대기) / SUCCESS / FAILED / REJECTED (CHECK)',
	`failure_reason`	VARCHAR(30)	NULL	COMMENT '실패 사유 코드',
	`order_id`	VARCHAR(100)	NULL	COMMENT '토스 orderId, 서버 발급 (중복결제 방지 UNIQUE)',
	`payment_key`	VARCHAR(200)	NULL	COMMENT '토스 paymentKey (승인 후 저장, 취소/환불에 사용)',
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '시도 일시',
	`updated_at`	DATETIME	NULL	COMMENT '상태 변경 일시 (PENDING→확정)'
);

CREATE TABLE `T_MCC_CTGR_C` (
	`id`	BIGINT	NOT NULL	COMMENT '업종 카테고리 아이디',
	`name`	VARCHAR(50)	NOT NULL	COMMENT '업종 카테고리명: 편의점/문구/PC방/노래방 등',
	`default_policy`	VARCHAR(50)	NOT NULL	DEFAULT 'ALLOW'	COMMENT '시스템 기본정책: ALLOW(허용)/WATCH(관찰)/BLOCK(차단) (CHECK)',
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '생성 일시'
);

CREATE TABLE `T_MBR_CONN_R` (
	`id`	BIGINT	NOT NULL	COMMENT '연동 아이디',
	`parent_id`	BIGINT	NOT NULL	COMMENT '부모 회원 아이디 (FK member)',
	`child_id`	BIGINT	NOT NULL	COMMENT '자녀 회원 아이디 (FK member, 부모+자녀 UNIQUE)',
	`status`	VARCHAR(20)	NOT NULL	DEFAULT 'ACTIVE'	COMMENT '상태: ACTIVE(연동) / INACTIVE(해제) (CHECK)',
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '연동 일시',
	`updated_at`	DATETIME	NULL	COMMENT '수정 일시'
);

CREATE TABLE `T_DPT_ENROLL_M` (
	`id`	BIGINT	NOT NULL	COMMENT '예금 가입 정보 아이디',
	`deposit_id`	BIGINT	NOT NULL	COMMENT '예금 상품 아이디',
	`child_id`	BIGINT	NOT NULL	COMMENT '가입 자녀 (FK member) (INDEX)',
	`parent_id`	BIGINT	NOT NULL	COMMENT '자녀와 연결된 부모 (FK member) (INDEX)',
	`wallet_id`	BIGINT	NOT NULL	COMMENT '예치금 관리 지갑 아이디 (UNIQUE)',
	`applied_rate`	DECIMAL(5, 2)	NOT NULL	COMMENT '가입시점 확정 금리 = 기본금리 + 등급 우대금리 (스냅샷, 만기까지 고정) (양수인지 CHECK)',
	`applied_early_termination_rate`	DECIMAL(5, 2)	NOT NULL	COMMENT '가입시점 중도해지시 적용 금리 스냅샷 (양수인지 CHECK)',
	`term_months`	SMALLINT	NOT NULL	COMMENT '가입 기간 (1개월,3개월,6개월,12개월 CHECK)',
	`start_date`	DATE	NULL	COMMENT '가입 확정일 (승인 후 설정)',
	`maturity_date`	DATE	NULL	COMMENT '만기일',
	`status`	VARCHAR(20)	NOT NULL	DEFAULT 'PENDING'	COMMENT '상태: PENDING(승인대기)/REJECTED(거절)/ACTIVE(진행중)/MATURED(만기)/TERMINATED(중도해지) (CHECK)',
	`closed_at`	DATETIME	NULL	COMMENT '만기/중도해지 처리 일시',
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '신청 일시',
	`updated_at`	DATETIME	NULL	COMMENT '수정 일시'
);

CREATE TABLE `T_WLT_BASE_M` (
	`id`	BIGINT	NOT NULL	COMMENT '지갑 아이디',
	`member_id`	BIGINT	NOT NULL	COMMENT '소유 회원 아이디 (FK member, INDEX)',
	`balance`	BIGINT	NOT NULL	DEFAULT 0	COMMENT '현재 잔액(원). 음수 불가, 갱신은 반드시 트랜잭션 내 처리 (0 이상인지 CHECK)',
	`type`	VARCHAR(20)	NOT NULL	COMMENT '타입: MEMBER(회원) / DEPOSIT(예금) / SAVING(적금) (CHECK)',
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '생성 일시',
	`updated_at`	DATETIME	NULL	COMMENT '수정 일시'
);

CREATE TABLE `T_WLT_HIST_H` (
	`id`	BIGINT	NOT NULL	COMMENT '지갑 변동 내역 아이디',
	`wallet_id`	BIGINT	NOT NULL	COMMENT '거래 발생 지갑 (FK wallet) (INDEX)',
	`payment_id`	BIGINT	NULL	COMMENT '결제 아이디',
	`transfer_id`	BIGINT	NULL	COMMENT '송금 아이디 (용돈, 예적금, 대출, 이자 등)',
	`charge_id`	BIGINT	NULL	COMMENT '충전 아이디 (결제, 송금, 충전 중 하나만 NULL이 아니도록 CHECK)',
	`direction`	VARCHAR(20)	NOT NULL	COMMENT '방향: CREDIT(입금) / DEBIT(출금) (CHECK)',
	`amount`	BIGINT	NOT NULL	COMMENT '거래 금액 (항상 양수 CHECK)',
	`balance_after`	BIGINT	NOT NULL	COMMENT '거래 후 잔액 스냅샷 (내역 화면 표시용) (0 이상 CHECK)',
	`description`	VARCHAR(255)	NULL	COMMENT '거래 설명 (화면 표시용)',
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '거래 일시'
);

CREATE TABLE `T_TNY_GRADE_A` (
	`grade_id`	BIGINT	NOT NULL	COMMENT '등급 아이디 (참조용 상수 테이블)',
	`grade_name`	VARCHAR(20)	NOT NULL	COMMENT '등급명: 회복필요/주의/보통/양호/우수 (UNIQUE)',
	`min_score`	SMALLINT	NOT NULL	COMMENT '등급 구간 최소 점수',
	`max_score`	SMALLINT	NOT NULL	COMMENT '등급 구간 최대 점수 (trust_score BETWEEN 조회로 등급 판정)',
	`bonus_rate`	DECIMAL(5, 2)	NOT NULL	DEFAULT 0.00	COMMENT '예적금 우대금리(%p)',
	`monthly_override_limit`	TINYINT	NOT NULL	DEFAULT 0	COMMENT '월간 오늘만 허용 요청 가능 횟수',
	`color`	VARCHAR(7)	NULL	COMMENT '등급 표시 색상 HEX'
);

CREATE TABLE `T_LON_PROD_M` (
	`id`	BIGINT	NOT NULL	COMMENT '대출 상품 아이디',
	`name`	VARCHAR(100)	NOT NULL	COMMENT '상품명 (UNIQUE)',
	`base_rate`	DECIMAL(5, 2)	NOT NULL	COMMENT '기본 연금리/연이자율(%) (양수인지 CHECK)',
	`late_fee_rate`	DECIMAL(5, 2)	NOT NULL	COMMENT '연체 이자율(%) (양수인지 CHECK)',
	`repayment_type`	VARCHAR(30)	NOT NULL	COMMENT '상환 방식: EQUAL_PRINCIPAL_INTEREST(원리금 균등 상환) / EQUAL_PRINCIPAL(원금 균등 상환) / BULLET(만기 일시 상환) (CHECK)',
	`min_amount`	BIGINT	NOT NULL	COMMENT '최소 대출 금액 (양수인지 CHECK)',
	`max_amount`	BIGINT	NOT NULL	COMMENT '최대 대출 금액 (양수인지 CHECK)',
	`min_teeny_score`	SMALLINT	NOT NULL	DEFAULT 0	COMMENT '가입 요구 최소 티니점수 (0 이상인지 CHECK)',
	`description`	TEXT	NULL	COMMENT '상품 설명',
	`is_active`	BOOLEAN	NOT NULL	DEFAULT TRUE	COMMENT '판매중 여부',
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록 일시',
	`updated_at`	DATETIME	NULL	COMMENT '수정 일시'
);

CREATE TABLE `T_SVG_PROD_M` (
	`id`	BIGINT	NOT NULL	COMMENT '적금 상품 아이디',
	`name`	VARCHAR(100)	NOT NULL	COMMENT '상품명 (UNIQUE)',
	`savings_type`	VARCHAR(10)	NOT NULL	COMMENT '적금 전용: FREE(자유적금) / FIXED(정기적금) (CHECK)',
	`interest_calculation_type`	VARCHAR(20)	NOT NULL	COMMENT '금리 계산 방식: SIMPLE(단리) / COMPOUND(복리) (CHECK)',
	`rate_1m`	DECIMAL(5, 2)	NULL	COMMENT '1개월 가입 시 금리 (NULL 시 가입 불가) (양수인지 CHECK)',
	`rate_3m`	DECIMAL(5, 2)	NULL	COMMENT '3개월 가입 시 금리 (양수인지 CHECK)',
	`rate_6m`	DECIMAL(5, 2)	NULL	COMMENT '6개월 가입 시 금리 (양수인지 CHECK)',
	`rate_12m`	DECIMAL(5, 2)	NULL	COMMENT '12개월 가입 시 금리 (양수인지 CHECK)',
	`early_termination_rate`	DECIMAL(5, 2)	NULL	COMMENT '중도해지시 적용 낮은 금리(%) (양수인지 CHECK)',
	`min_month_amount`	BIGINT	NOT NULL	COMMENT '최소 월 납입액 (정기적금만 해당) (양수인지 CHECK)',
	`max_month_amount`	BIGINT	NOT NULL	COMMENT '최대 월 납입액 한도 (양수인지 CHECK)',
	`min_teeny_score`	SMALLINT	NOT NULL	DEFAULT 0	COMMENT '가입 요구 최소 티니점수 (0 이상인지 CHECK)',
	`description`	TEXT	NULL	COMMENT '상품 설명',
	`is_active`	BOOLEAN	NOT NULL	DEFAULT TRUE	COMMENT '판매중 여부',
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록 일시',
	`updated_at`	DATETIME	NULL	COMMENT '수정 일시'
);

CREATE TABLE `T_DPT_PROD_M` (
	`id`	BIGINT	NOT NULL	COMMENT '예금 상품 아이디',
	`name`	VARCHAR(100)	NOT NULL	COMMENT '상품명 (UNIQUE)',
	`rate_1m`	DECIMAL(5, 2)	NULL	COMMENT '1개월 가입 시 금리 (NULL 시 가입 불가) (양수인지 CHECK)',
	`rate_3m`	DECIMAL(5, 2)	NULL	COMMENT '3개월 가입 시 금리 (양수인지 CHECK)',
	`rate_6m`	DECIMAL(5, 2)	NULL	COMMENT '6개월 가입 시 금리 (양수인지 CHECK)',
	`rate_12m`	DECIMAL(5, 2)	NULL	COMMENT '12개월 가입 시 금리 (양수인지 CHECK)',
	`early_termination_rate`	DECIMAL(5, 2)	NOT NULL	COMMENT '중도해지시 적용 낮은 금리(%) (양수인지 CHECK)',
	`min_amount`	BIGINT	NOT NULL	COMMENT '최소 예금액 (양수인지 CHECK)',
	`max_amount`	BIGINT	NOT NULL	COMMENT '최대 예금액 (양수인지 CHECK)',
	`min_teeny_score`	SMALLINT	NOT NULL	DEFAULT 0	COMMENT '가입 요구 최소 티니점수 (0 이상인지 CHECK)',
	`description`	TEXT	NULL	COMMENT '상품 설명',
	`is_active`	BOOLEAN	NOT NULL	DEFAULT TRUE	COMMENT '판매중 여부',
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록 일시',
	`updated_at`	DATETIME	NULL	COMMENT '수정 일시'
);

CREATE TABLE `T_NTF_NOTI_L` (
	`id`	BIGINT	NOT NULL	COMMENT '알림 아이디',
	`member_id`	BIGINT	NOT NULL	COMMENT '수신 회원 (FK member) (INDEX)',
	`type`	VARCHAR(20)	NOT NULL	COMMENT '알림 유형: QUEST/PAYMENT/FINANCE/ALLOWANCE/OVERRIDE(오늘만허용) (CHECK)',
	`content`	VARCHAR(500)	NULL	COMMENT '알림 내용',
	`reference_type`	VARCHAR(50)	NULL	COMMENT '딥링크 대상 테이블: QUEST/TODAY_PERMISSION/CONNECTION/TRANSFER/PAYMENT/CHARGE/DEPOSIT_ENROLLMENT/SAVING_ENROLLMENT/LOAN_ENROLLMENT (CHECK)',
	`reference_id`	BIGINT	NULL	COMMENT '딥링크 대상 아이디',
	`is_read`	BOOLEAN	NOT NULL	DEFAULT FALSE	COMMENT '읽음 여부',
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '발송 일시',
	`updated_at`	DATETIME	NULL	COMMENT '수정 일시'
);

CREATE TABLE `T_WLT_CHARGE_L` (
	`id`	BIGINT	NOT NULL	COMMENT '충전 아이디',
	`wallet_id`	BIGINT	NOT NULL	COMMENT '충전한 지갑 (FK wallet) (INDEX)',
	`payment_method_id`	BIGINT	NOT NULL	COMMENT '결제수단 아이디',
	`idempotency_key`	CHAR(36)	NOT NULL	COMMENT '멱등성 키 (UUID) (UNIQUE)',
	`amount`	BIGINT	NOT NULL	COMMENT '충전 금액',
	`status`	VARCHAR(10)	NOT NULL	DEFAULT 'PENDING'	COMMENT '결과: PENDING(토스 승인대기) / SUCCESS / FAILED (CHECK)',
	`failure_reason`	VARCHAR(30)	NULL	COMMENT '실패 사유 코드',
	`order_id`	VARCHAR(100)	NULL	COMMENT '토스 orderId, 서버 발급 (중복결제 방지 UNIQUE)',
	`payment_key`	VARCHAR(200)	NULL	COMMENT '토스 paymentKey (승인 후 저장, 취소/환불에 사용)',
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '시도 일시',
	`updated_at`	DATETIME	NULL	COMMENT '상태 변경 일시 (PENDING→확정)'
);

CREATE TABLE `T_TNY_SCOREHIST_H` (
	`id`	BIGINT	NOT NULL	COMMENT '신뢰도 이력 아이디',
	`child_id`	BIGINT	NOT NULL	COMMENT '대상 자녀 (FK member) (INDEX)',
	`amount`	SMALLINT	NOT NULL	COMMENT '변동량 (음수 가능: 연체/중도해지 등)',
	`score_after`	SMALLINT	NOT NULL	COMMENT '변동 후 점수 (0~1000) (CHECK)',
	`description`	VARCHAR(100)	NOT NULL	COMMENT '설명: 퀘스트성공/대출연체/적금중도해지 등',
	`reference_type`	VARCHAR(50)	NULL	COMMENT '참조 테이블: QUEST/TODAY_PERMISSION/CONNECTION/TRANSFER/PAYMENT/CHARGE/DEPOSIT_ENROLLMENT/SAVING_ENROLLMENT/LOAN_ENROLLMENT (CHECK)',
	`reference_id`	BIGINT	NULL	COMMENT '참조 테이블 아이디',
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '생성 일시'
);

CREATE TABLE `T_QST_VERIFY_L` (
	`id`	BIGINT	NOT NULL	COMMENT '퀘스트 인증 아이디',
	`quest_id`	BIGINT	NOT NULL	COMMENT '대상 퀘스트 (FK quest) (INDEX)',
	`image_url`	VARCHAR(1024)	NULL	COMMENT '실시간 촬영 인증사진 URL',
	`content`	VARCHAR(500)	NULL	COMMENT '인증 텍스트',
	`status`	VARCHAR(10)	NOT NULL	DEFAULT 'PENDING'	COMMENT '상태: PENDING(대기)/APPROVED(승인)/REJECTED(거절) (CHECK)',
	`rejection_reason`	VARCHAR(255)	NULL	COMMENT '거절 사유',
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '생성 일시',
	`updated_at`	DATETIME	NULL	COMMENT '수정 일시',
	`reviewed_at`	DATETIME	NULL	COMMENT '부모 검토 일시'
);

CREATE TABLE `T_TDP_REQCTGR_R` (
	`today_permission_id`	BIGINT	NOT NULL	COMMENT '오늘만 허용 아이디',
	`merchant_category_id`	BIGINT	NOT NULL	COMMENT '업종 카테고리 아이디',
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '생성 일시'
);

CREATE TABLE `T_ALW_SCHEDULE_M` (
	`id`	BIGINT	NOT NULL	COMMENT '정기 용돈 설정 아이디',
	`parent_id`	BIGINT	NOT NULL	COMMENT '지급 부모 (FK member)',
	`child_id`	BIGINT	NOT NULL	COMMENT '수령 자녀 (FK member, 부모-자녀당 1건 UNIQUE)',
	`amount`	BIGINT	NOT NULL	COMMENT '회당 지급 금액 (양수인지 CHECK)',
	`cycle_type`	VARCHAR(20)	NOT NULL	COMMENT '주기: WEEKLY(매주) / MONTHLY(매달) (CHECK)',
	`payment_day`	TINYINT	NOT NULL	COMMENT '지급일: WEEKLY=요일(1~7), MONTHLY=일자(1~28) (CHECK)',
	`next_payment_date`	DATE	NOT NULL	COMMENT '다음 지급 예정일 (배치 조회 기준) (INDEX)',
	`is_active`	BOOLEAN	NOT NULL	DEFAULT TRUE	COMMENT '활성 여부',
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '생성 일시',
	`updated_at`	DATETIME	NULL	COMMENT '수정 일시'
);

CREATE TABLE `T_LON_ENROLL_M` (
	`id`	BIGINT	NOT NULL	COMMENT '대출 계좌 아이디',
	`loan_id`	BIGINT	NOT NULL	COMMENT '대출 상품 아이디',
	`parent_id`	BIGINT	NOT NULL	COMMENT '자녀와 연결된 부모 (채권자) (INDEX)',
	`child_id`	BIGINT	NOT NULL	COMMENT '대출 자녀 (채무자) (INDEX)',
	`principal_amount`	BIGINT	NOT NULL	COMMENT '대출 원금 (고정) (양수인지 CHECK)',
	`outstanding_principal`	BIGINT	NOT NULL	COMMENT '남은 원금 (상환시 감소 캐시) (0 이상인지 CHECK)',
	`overdue_interest`	BIGINT	NOT NULL	DEFAULT 0	COMMENT '누적 미납 이자 (0 이상인지 CHECK)',
	`applied_rate`	DECIMAL(5, 2)	NOT NULL	COMMENT '가입시점 기준 이자율 스냅샷 (실제 월이자는 상환일 신뢰점수로 재계산) (양수인지 CHECK)',
	`applied_late_fee_rate`	DECIMAL(5, 2)	NOT NULL	COMMENT '가입 시점 연체 이자율(%) 스냅샷 (양수인지 CHECK)',
	`auto_transfer`	BOOLEAN	NOT NULL	DEFAULT FALSE	COMMENT '이자 자동이체 여부',
	`payment_day`	TINYINT	NOT NULL	COMMENT '매월 상환일 1~28 (CHECK)',
	`paid_count`	SMALLINT	NOT NULL	COMMENT '성공적으로 지불한 횟수',
	`term_months`	SMALLINT	NOT NULL	COMMENT '대출 상환 기간 (개월 수)',
	`start_date`	DATE	NULL	COMMENT '대출 실행일',
	`maturity_date`	DATE	NULL	COMMENT '만기일',
	`status`	VARCHAR(20)	NOT NULL	DEFAULT 'PENDING'	COMMENT '상태: PENDING(승인대기)/REJECTED(거절)/ACTIVE(상환중)/OVERDUE(연체중)/REPAID(완제) (CHECK)',
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '신청 일시',
	`updated_at`	DATETIME	NULL	COMMENT '수정 일시'
);

CREATE TABLE `T_QST_BASE_M` (
	`id`	BIGINT	NOT NULL	COMMENT '퀘스트 아이디',
	`parent_id`	BIGINT	NOT NULL	COMMENT '생성한 부모 (FK member) (INDEX)',
	`child_id`	BIGINT	NOT NULL	COMMENT '수행할 자녀 (FK member) (INDEX)',
	`title`	VARCHAR(100)	NOT NULL	COMMENT '퀘스트 제목',
	`content`	VARCHAR(500)	NULL	COMMENT '상세 내용',
	`deadline`	DATETIME	NOT NULL	COMMENT '수행 마감 일시',
	`is_teeny_score`	BOOLEAN	NOT NULL	DEFAULT FALSE	COMMENT '티니점수 제공 여부',
	`reward_amount`	BIGINT	NOT NULL	COMMENT '완료 시 보상 금액(원) (0 이상인지 CHECK)',
	`reward_teeny_score`	SMALLINT	NOT NULL	DEFAULT 0	COMMENT '완료 시 티니점수 보상 (0 이상인지 CHECK)',
	`status`	VARCHAR(20)	NOT NULL	DEFAULT 'AVAILABLE'	COMMENT '상태: AVAILABLE(시작가능)/IN_PROGRESS(진행중)/PENDING(승인대기)/COMPLETED(성공)/FAILED(실패) (CHECK)',
	`remaining_count`	TINYINT	NOT NULL	DEFAULT 3	COMMENT '남은 제출 기회',
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '생성 일시',
	`updated_at`	DATETIME	NULL	COMMENT '수정 일시',
	`completed_at`	DATETIME	NULL	COMMENT '최종 완료 일시 (성공/실패)'
);

CREATE TABLE `T_MBR_INFO_M` (
	`id`	BIGINT	NOT NULL	COMMENT '회원 테이블 아이디',
	`role`	VARCHAR(20)	NOT NULL	COMMENT '역할: PARENT(부모) / CHILD(자녀) (CHECK)',
	`name`	VARCHAR(50)	NOT NULL	COMMENT '이름',
	`birth_date`	DATE	NOT NULL	COMMENT '생년월일',
	`phone_number`	VARCHAR(20)	NOT NULL	COMMENT '휴대폰 번호 (연락처당 1계정, UNIQUE)',
	`email`	VARCHAR(100)	NOT NULL	COMMENT '로그인 이메일 (UNIQUE)',
	`password`	VARCHAR(255)	NOT NULL	COMMENT '로그인 비밀번호',
	`social_login_type`	VARCHAR(20)	NULL	COMMENT '소셜 로그인 타입',
	`social_login_id`	VARCHAR(1024)	NULL	COMMENT '소셜 로그인 식별자',
	`payment_password`	VARCHAR(255)	NULL	COMMENT '결제 비밀번호 (자녀만 사용)',
	`payment_password_failed_count`	TINYINT	NOT NULL	DEFAULT 0	COMMENT '결제 비밀번호 연속 실패 횟수 (5회시 잠금)',
	`payment_locked_until`	DATETIME	NULL	COMMENT '결제 잠금 해제 예정 일시',
	`profile_image_url`	VARCHAR(1024)	NULL	COMMENT '프로필 이미지 URL',
	`teeny_score`	SMALLINT	NULL	DEFAULT 600	COMMENT '티니점수 0~1000 (CHECK), 초기 600 (자녀만 사용)',
	`customer_key`	VARCHAR(100)	NULL	COMMENT '토스 빌링용 구매자 UUID (부모만 사용)',
	`fcm_token`	VARCHAR(255)	NULL	COMMENT 'FCM 푸시 토큰, 로그아웃시 NULL',
	`noti_payment`	BOOLEAN	NOT NULL	DEFAULT TRUE	COMMENT '결제/유해업종 알림 수신 여부',
	`noti_quest`	BOOLEAN	NOT NULL	DEFAULT TRUE	COMMENT '퀘스트 알림 수신 여부',
	`noti_finance`	BOOLEAN	NOT NULL	DEFAULT TRUE	COMMENT '예적금/대출 알림 수신 여부',
	`noti_allowance`	BOOLEAN	NOT NULL	DEFAULT TRUE	COMMENT '용돈/잔액 알림 수신 여부',
	`status`	VARCHAR(20)	NOT NULL	DEFAULT 'ACTIVE'	COMMENT '상태: ACTIVE / INACTIVE (CHECK)',
	`inactive_date`	DATE	NULL	COMMENT '비활성화 일자',
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '가입 일시',
	`updated_at`	DATETIME	NULL	COMMENT '수정 일시'
);

CREATE TABLE `T_MCC_CODE_C` (
	`id`	CHARACTER(6)	NOT NULL	COMMENT 'MCC 코드를 아이디로 사용',
	`merchant_category_id`	BIGINT	NOT NULL	COMMENT '업종 카테고리 아이디',
	`name`	VARCHAR(100)	NOT NULL	COMMENT '업종 이름',
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '생성 일시'
);

CREATE TABLE `T_SVG_ENROLL_M` (
	`id`	BIGINT	NOT NULL	COMMENT '적금 가입 정보 아이디',
	`saving_id`	BIGINT	NOT NULL	COMMENT '적금 상품 아이디',
	`child_id`	BIGINT	NOT NULL	COMMENT '가입 자녀 (FK member) (INDEX)',
	`parent_id`	BIGINT	NOT NULL	COMMENT '자녀와 연결된 부모 (FK member) (INDEX)',
	`wallet_id`	BIGINT	NOT NULL	COMMENT '누적 납입액 관리 지갑 아이디 (UNIQUE)',
	`applied_rate`	DECIMAL(5, 2)	NOT NULL	COMMENT '가입시점 확정 금리 = 기본금리 + 등급 우대금리 (스냅샷, 만기까지 고정) (양수인지 CHECK)',
	`applied_early_termination_rate`	DECIMAL(5, 2)	NOT NULL	COMMENT '가입시점 중도해지시 적용 금리 스냅샷 (양수인지 CHECK)',
	`term_months`	SMALLINT	NOT NULL	COMMENT '가입 기간 (개월 수) (1개월,3개월,6개월,12개월 CHECK)',
	`monthly_amount`	BIGINT	NULL	COMMENT '적금 전용: 월 납입 약정액 (양수인지 CHECK)',
	`payment_day`	TINYINT	NULL	COMMENT '적금 전용: 매월 납입일 1~28 (CHECK)',
	`auto_transfer`	BOOLEAN	NOT NULL	DEFAULT FALSE	COMMENT '적금 전용: 자동이체 여부',
	`start_date`	DATE	NULL	COMMENT '가입 확정일 (부모 승인 후 UPDATE)',
	`maturity_date`	DATE	NULL	COMMENT '만기일',
	`status`	VARCHAR(20)	NOT NULL	DEFAULT 'PENDING'	COMMENT '상태: PENDING(승인대기)/REJECTED(거절)/ACTIVE(진행중)/MATURED(만기)/TERMINATED(중도해지) (CHECK)',
	`closed_at`	DATETIME	NULL	COMMENT '만기/중도해지 처리 일시',
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '신청 일시',
	`updated_at`	DATETIME	NULL	COMMENT '수정 일시'
);

CREATE TABLE `T_SVG_PAYHIST_H` (
	`id`	BIGINT	NOT NULL	COMMENT '적금 납입 이력 시퀀스',
	`saving_enrollment_id`	BIGINT	NOT NULL	COMMENT '적금 가입 정보 아이디 (INDEX)',
	`transfer_id`	BIGINT	NULL	COMMENT '송금 시도 아이디 (UNIQUE)',
	`installment_no`	SMALLINT	NOT NULL	COMMENT '납입 회차',
	`amount`	BIGINT	NULL	COMMENT '정기적금 전용: 납입 예정액 (양수인지 CHECK)',
	`paid_amount`	BIGINT	NOT NULL	COMMENT '납입 금액 (양수인지 CHECK)',
	`status`	VARCHAR(10)	NOT NULL	COMMENT 'PAID(납입완료)/MISSED(미납)/PARTIAL(부분납입) (CHECK)',
	`created_at`	DATETIME	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '생성 일시',
	`paid_at`	DATETIME	NULL	COMMENT '실제 납입 일시'
);

-- ============================================================
-- PRIMARY KEY
-- ============================================================

ALTER TABLE `T_PAY_METHOD_M` MODIFY `id`	BIGINT	NOT NULL	AUTO_INCREMENT	COMMENT '결제수단 아이디',
	ADD CONSTRAINT `PK_PAY_METHOD_M` PRIMARY KEY (`id`);
ALTER TABLE `T_WLT_TRF_L` MODIFY `id`	BIGINT	NOT NULL	AUTO_INCREMENT	COMMENT '송금 아이디 (용돈, 예적금, 대출, 이자 등)',
	ADD CONSTRAINT `PK_WLT_TRF_L` PRIMARY KEY (`id`);
ALTER TABLE `T_MCC_POLICY_M` MODIFY `id`	BIGINT	NOT NULL	AUTO_INCREMENT	COMMENT '자녀별 커스텀 정책 아이디',
	ADD CONSTRAINT `PK_MCC_POLICY_M` PRIMARY KEY (`id`);
ALTER TABLE `T_TDP_REQ_L` MODIFY `id`	BIGINT	NOT NULL	AUTO_INCREMENT	COMMENT '오늘만 허용 요청 아이디',
	ADD CONSTRAINT `PK_TDP_REQ_L` PRIMARY KEY (`id`);
ALTER TABLE `T_LON_REPAYHIST_H` MODIFY `id`	BIGINT	NOT NULL	AUTO_INCREMENT	COMMENT '대출 상환 이력 시퀀스',
	ADD CONSTRAINT `PK_LON_REPAYHIST_H` PRIMARY KEY (`id`);
ALTER TABLE `T_PAY_TRAN_L` MODIFY `id`	BIGINT	NOT NULL	AUTO_INCREMENT	COMMENT '결제 아이디',
	ADD CONSTRAINT `PK_PAY_TRAN_L` PRIMARY KEY (`id`);
ALTER TABLE `T_MCC_CTGR_C` MODIFY `id`	BIGINT	NOT NULL	AUTO_INCREMENT	COMMENT '업종 카테고리 아이디',
	ADD CONSTRAINT `PK_MCC_CTGR_C` PRIMARY KEY (`id`);
ALTER TABLE `T_MBR_CONN_R` MODIFY `id`	BIGINT	NOT NULL	AUTO_INCREMENT	COMMENT '연동 아이디',
	ADD CONSTRAINT `PK_MBR_CONN_R` PRIMARY KEY (`id`);
ALTER TABLE `T_DPT_ENROLL_M` MODIFY `id`	BIGINT	NOT NULL	AUTO_INCREMENT	COMMENT '예금 가입 정보 아이디',
	ADD CONSTRAINT `PK_DPT_ENROLL_M` PRIMARY KEY (`id`);
ALTER TABLE `T_WLT_BASE_M` MODIFY `id`	BIGINT	NOT NULL	AUTO_INCREMENT	COMMENT '지갑 아이디',
	ADD CONSTRAINT `PK_WLT_BASE_M` PRIMARY KEY (`id`);
ALTER TABLE `T_WLT_HIST_H` MODIFY `id`	BIGINT	NOT NULL	AUTO_INCREMENT	COMMENT '지갑 변동 내역 아이디',
	ADD CONSTRAINT `PK_WLT_HIST_H` PRIMARY KEY (`id`);
ALTER TABLE `T_TNY_GRADE_A` MODIFY `grade_id`	BIGINT	NOT NULL	AUTO_INCREMENT	COMMENT '등급 아이디 (참조용 상수 테이블)',
	ADD CONSTRAINT `PK_TNY_GRADE_A` PRIMARY KEY (`grade_id`);
ALTER TABLE `T_LON_PROD_M` MODIFY `id`	BIGINT	NOT NULL	AUTO_INCREMENT	COMMENT '대출 상품 아이디',
	ADD CONSTRAINT `PK_LON_PROD_M` PRIMARY KEY (`id`);
ALTER TABLE `T_SVG_PROD_M` MODIFY `id`	BIGINT	NOT NULL	AUTO_INCREMENT	COMMENT '적금 상품 아이디',
	ADD CONSTRAINT `PK_SVG_PROD_M` PRIMARY KEY (`id`);
ALTER TABLE `T_DPT_PROD_M` MODIFY `id`	BIGINT	NOT NULL	AUTO_INCREMENT	COMMENT '예금 상품 아이디',
	ADD CONSTRAINT `PK_DPT_PROD_M` PRIMARY KEY (`id`);
ALTER TABLE `T_NTF_NOTI_L` MODIFY `id`	BIGINT	NOT NULL	AUTO_INCREMENT	COMMENT '알림 아이디',
	ADD CONSTRAINT `PK_NTF_NOTI_L` PRIMARY KEY (`id`);
ALTER TABLE `T_WLT_CHARGE_L` MODIFY `id`	BIGINT	NOT NULL	AUTO_INCREMENT	COMMENT '충전 아이디',
	ADD CONSTRAINT `PK_WLT_CHARGE_L` PRIMARY KEY (`id`);
ALTER TABLE `T_TNY_SCOREHIST_H` MODIFY `id`	BIGINT	NOT NULL	AUTO_INCREMENT	COMMENT '신뢰도 이력 아이디',
	ADD CONSTRAINT `PK_TNY_SCOREHIST_H` PRIMARY KEY (`id`);
ALTER TABLE `T_QST_VERIFY_L` MODIFY `id`	BIGINT	NOT NULL	AUTO_INCREMENT	COMMENT '퀘스트 인증 아이디',
	ADD CONSTRAINT `PK_QST_VERIFY_L` PRIMARY KEY (`id`);
ALTER TABLE `T_TDP_REQCTGR_R` ADD CONSTRAINT `PK_TDP_REQCTGR_R` PRIMARY KEY (`today_permission_id`, `merchant_category_id`);
ALTER TABLE `T_ALW_SCHEDULE_M` MODIFY `id`	BIGINT	NOT NULL	AUTO_INCREMENT	COMMENT '정기 용돈 설정 아이디',
	ADD CONSTRAINT `PK_ALW_SCHEDULE_M` PRIMARY KEY (`id`);
ALTER TABLE `T_LON_ENROLL_M` MODIFY `id`	BIGINT	NOT NULL	AUTO_INCREMENT	COMMENT '대출 계좌 아이디',
	ADD CONSTRAINT `PK_LON_ENROLL_M` PRIMARY KEY (`id`);
ALTER TABLE `T_QST_BASE_M` MODIFY `id`	BIGINT	NOT NULL	AUTO_INCREMENT	COMMENT '퀘스트 아이디',
	ADD CONSTRAINT `PK_QST_BASE_M` PRIMARY KEY (`id`);
ALTER TABLE `T_MBR_INFO_M` MODIFY `id`	BIGINT	NOT NULL	AUTO_INCREMENT	COMMENT '회원 테이블 아이디',
	ADD CONSTRAINT `PK_MBR_INFO_M` PRIMARY KEY (`id`);
ALTER TABLE `T_MCC_CODE_C` ADD CONSTRAINT `PK_MCC_CODE_C` PRIMARY KEY (`id`);
ALTER TABLE `T_SVG_ENROLL_M` MODIFY `id`	BIGINT	NOT NULL	AUTO_INCREMENT	COMMENT '적금 가입 정보 아이디',
	ADD CONSTRAINT `PK_SVG_ENROLL_M` PRIMARY KEY (`id`);
ALTER TABLE `T_SVG_PAYHIST_H` MODIFY `id`	BIGINT	NOT NULL	AUTO_INCREMENT	COMMENT '적금 납입 이력 시퀀스',
	ADD CONSTRAINT `PK_SVG_PAYHIST_H` PRIMARY KEY (`id`);

-- ============================================================
-- FOREIGN KEY
-- ============================================================

ALTER TABLE `T_MBR_CONN_R` ADD CONSTRAINT `FK_T_MBR_INFO_M_TO_T_MBR_CONN_R_1`
	FOREIGN KEY (`parent_id`) REFERENCES `T_MBR_INFO_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_MBR_CONN_R` ADD CONSTRAINT `FK_T_MBR_INFO_M_TO_T_MBR_CONN_R_2`
	FOREIGN KEY (`child_id`) REFERENCES `T_MBR_INFO_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_MCC_POLICY_M` ADD CONSTRAINT `FK_T_MBR_INFO_M_TO_T_MCC_POLICY_M_1`
	FOREIGN KEY (`parent_id`) REFERENCES `T_MBR_INFO_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_MCC_POLICY_M` ADD CONSTRAINT `FK_T_MBR_INFO_M_TO_T_MCC_POLICY_M_2`
	FOREIGN KEY (`child_id`) REFERENCES `T_MBR_INFO_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_MCC_POLICY_M` ADD CONSTRAINT `FK_T_MCC_CTGR_C_TO_T_MCC_POLICY_M_1`
	FOREIGN KEY (`merchant_category_id`) REFERENCES `T_MCC_CTGR_C` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_TDP_REQ_L` ADD CONSTRAINT `FK_T_MBR_INFO_M_TO_T_TDP_REQ_L_1`
	FOREIGN KEY (`parent_id`) REFERENCES `T_MBR_INFO_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_TDP_REQ_L` ADD CONSTRAINT `FK_T_MBR_INFO_M_TO_T_TDP_REQ_L_2`
	FOREIGN KEY (`child_id`) REFERENCES `T_MBR_INFO_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_TDP_REQCTGR_R` ADD CONSTRAINT `FK_T_TDP_REQ_L_TO_T_TDP_REQCTGR_R_1`
	FOREIGN KEY (`today_permission_id`) REFERENCES `T_TDP_REQ_L` (`id`) ON DELETE CASCADE;

ALTER TABLE `T_TDP_REQCTGR_R` ADD CONSTRAINT `FK_T_MCC_CTGR_C_TO_T_TDP_REQCTGR_R_1`
	FOREIGN KEY (`merchant_category_id`) REFERENCES `T_MCC_CTGR_C` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_PAY_METHOD_M` ADD CONSTRAINT `FK_T_MBR_INFO_M_TO_T_PAY_METHOD_M_1`
	FOREIGN KEY (`parent_id`) REFERENCES `T_MBR_INFO_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_WLT_BASE_M` ADD CONSTRAINT `FK_T_MBR_INFO_M_TO_T_WLT_BASE_M_1`
	FOREIGN KEY (`member_id`) REFERENCES `T_MBR_INFO_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_WLT_TRF_L` ADD CONSTRAINT `FK_T_WLT_BASE_M_TO_T_WLT_TRF_L_1`
	FOREIGN KEY (`from_wallet_id`) REFERENCES `T_WLT_BASE_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_WLT_TRF_L` ADD CONSTRAINT `FK_T_WLT_BASE_M_TO_T_WLT_TRF_L_2`
	FOREIGN KEY (`to_wallet_id`) REFERENCES `T_WLT_BASE_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_WLT_CHARGE_L` ADD CONSTRAINT `FK_T_WLT_BASE_M_TO_T_WLT_CHARGE_L_1`
	FOREIGN KEY (`wallet_id`) REFERENCES `T_WLT_BASE_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_WLT_CHARGE_L` ADD CONSTRAINT `FK_T_PAY_METHOD_M_TO_T_WLT_CHARGE_L_1`
	FOREIGN KEY (`payment_method_id`) REFERENCES `T_PAY_METHOD_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_PAY_TRAN_L` ADD CONSTRAINT `FK_T_WLT_BASE_M_TO_T_PAY_TRAN_L_1`
	FOREIGN KEY (`wallet_id`) REFERENCES `T_WLT_BASE_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_PAY_TRAN_L` ADD CONSTRAINT `FK_T_PAY_TRAN_L_TO_T_PAY_TRAN_L_1`
	FOREIGN KEY (`original_payment_id`) REFERENCES `T_PAY_TRAN_L` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_PAY_TRAN_L` ADD CONSTRAINT `FK_T_MCC_CTGR_C_TO_T_PAY_TRAN_L_1`
	FOREIGN KEY (`category_id`) REFERENCES `T_MCC_CTGR_C` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_WLT_HIST_H` ADD CONSTRAINT `FK_T_WLT_BASE_M_TO_T_WLT_HIST_H_1`
	FOREIGN KEY (`wallet_id`) REFERENCES `T_WLT_BASE_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_WLT_HIST_H` ADD CONSTRAINT `FK_T_PAY_TRAN_L_TO_T_WLT_HIST_H_1`
	FOREIGN KEY (`payment_id`) REFERENCES `T_PAY_TRAN_L` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_WLT_HIST_H` ADD CONSTRAINT `FK_T_WLT_TRF_L_TO_T_WLT_HIST_H_1`
	FOREIGN KEY (`transfer_id`) REFERENCES `T_WLT_TRF_L` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_WLT_HIST_H` ADD CONSTRAINT `FK_T_WLT_CHARGE_L_TO_T_WLT_HIST_H_1`
	FOREIGN KEY (`charge_id`) REFERENCES `T_WLT_CHARGE_L` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_DPT_ENROLL_M` ADD CONSTRAINT `FK_T_DPT_PROD_M_TO_T_DPT_ENROLL_M_1`
	FOREIGN KEY (`deposit_id`) REFERENCES `T_DPT_PROD_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_DPT_ENROLL_M` ADD CONSTRAINT `FK_T_MBR_INFO_M_TO_T_DPT_ENROLL_M_1`
	FOREIGN KEY (`child_id`) REFERENCES `T_MBR_INFO_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_DPT_ENROLL_M` ADD CONSTRAINT `FK_T_MBR_INFO_M_TO_T_DPT_ENROLL_M_2`
	FOREIGN KEY (`parent_id`) REFERENCES `T_MBR_INFO_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_DPT_ENROLL_M` ADD CONSTRAINT `FK_T_WLT_BASE_M_TO_T_DPT_ENROLL_M_1`
	FOREIGN KEY (`wallet_id`) REFERENCES `T_WLT_BASE_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_SVG_ENROLL_M` ADD CONSTRAINT `FK_T_SVG_PROD_M_TO_T_SVG_ENROLL_M_1`
	FOREIGN KEY (`saving_id`) REFERENCES `T_SVG_PROD_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_SVG_ENROLL_M` ADD CONSTRAINT `FK_T_MBR_INFO_M_TO_T_SVG_ENROLL_M_1`
	FOREIGN KEY (`child_id`) REFERENCES `T_MBR_INFO_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_SVG_ENROLL_M` ADD CONSTRAINT `FK_T_MBR_INFO_M_TO_T_SVG_ENROLL_M_2`
	FOREIGN KEY (`parent_id`) REFERENCES `T_MBR_INFO_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_SVG_ENROLL_M` ADD CONSTRAINT `FK_T_WLT_BASE_M_TO_T_SVG_ENROLL_M_1`
	FOREIGN KEY (`wallet_id`) REFERENCES `T_WLT_BASE_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_SVG_PAYHIST_H` ADD CONSTRAINT `FK_T_SVG_ENROLL_M_TO_T_SVG_PAYHIST_H_1`
	FOREIGN KEY (`saving_enrollment_id`) REFERENCES `T_SVG_ENROLL_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_SVG_PAYHIST_H` ADD CONSTRAINT `FK_T_WLT_TRF_L_TO_T_SVG_PAYHIST_H_1`
	FOREIGN KEY (`transfer_id`) REFERENCES `T_WLT_TRF_L` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_LON_ENROLL_M` ADD CONSTRAINT `FK_T_LON_PROD_M_TO_T_LON_ENROLL_M_1`
	FOREIGN KEY (`loan_id`) REFERENCES `T_LON_PROD_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_LON_ENROLL_M` ADD CONSTRAINT `FK_T_MBR_INFO_M_TO_T_LON_ENROLL_M_1`
	FOREIGN KEY (`parent_id`) REFERENCES `T_MBR_INFO_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_LON_ENROLL_M` ADD CONSTRAINT `FK_T_MBR_INFO_M_TO_T_LON_ENROLL_M_2`
	FOREIGN KEY (`child_id`) REFERENCES `T_MBR_INFO_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_LON_REPAYHIST_H` ADD CONSTRAINT `FK_T_LON_ENROLL_M_TO_T_LON_REPAYHIST_H_1`
	FOREIGN KEY (`loan_enrollment_id`) REFERENCES `T_LON_ENROLL_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_LON_REPAYHIST_H` ADD CONSTRAINT `FK_T_WLT_TRF_L_TO_T_LON_REPAYHIST_H_1`
	FOREIGN KEY (`transfer_id`) REFERENCES `T_WLT_TRF_L` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_MCC_CODE_C` ADD CONSTRAINT `FK_T_MCC_CTGR_C_TO_T_MCC_CODE_C_1`
	FOREIGN KEY (`merchant_category_id`) REFERENCES `T_MCC_CTGR_C` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_ALW_SCHEDULE_M` ADD CONSTRAINT `FK_T_MBR_INFO_M_TO_T_ALW_SCHEDULE_M_1`
	FOREIGN KEY (`parent_id`) REFERENCES `T_MBR_INFO_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_ALW_SCHEDULE_M` ADD CONSTRAINT `FK_T_MBR_INFO_M_TO_T_ALW_SCHEDULE_M_2`
	FOREIGN KEY (`child_id`) REFERENCES `T_MBR_INFO_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_QST_BASE_M` ADD CONSTRAINT `FK_T_MBR_INFO_M_TO_T_QST_BASE_M_1`
	FOREIGN KEY (`parent_id`) REFERENCES `T_MBR_INFO_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_QST_BASE_M` ADD CONSTRAINT `FK_T_MBR_INFO_M_TO_T_QST_BASE_M_2`
	FOREIGN KEY (`child_id`) REFERENCES `T_MBR_INFO_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_QST_VERIFY_L` ADD CONSTRAINT `FK_T_QST_BASE_M_TO_T_QST_VERIFY_L_1`
	FOREIGN KEY (`quest_id`) REFERENCES `T_QST_BASE_M` (`id`) ON DELETE CASCADE;

ALTER TABLE `T_TNY_SCOREHIST_H` ADD CONSTRAINT `FK_T_MBR_INFO_M_TO_T_TNY_SCOREHIST_H_1`
	FOREIGN KEY (`child_id`) REFERENCES `T_MBR_INFO_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_NTF_NOTI_L` ADD CONSTRAINT `FK_T_MBR_INFO_M_TO_T_NTF_NOTI_L_1`
	FOREIGN KEY (`member_id`) REFERENCES `T_MBR_INFO_M` (`id`) ON DELETE RESTRICT;

-- ============================================================
-- UNIQUE
-- ============================================================

ALTER TABLE `T_WLT_TRF_L` ADD CONSTRAINT `UQ_WLT_TRF_L_IDEMPOTENCY_KEY` UNIQUE (`idempotency_key`);
ALTER TABLE `T_MCC_POLICY_M` ADD CONSTRAINT `UQ_MCC_POLICY_M_CHILD_CATEGORY` UNIQUE (`child_id`, `merchant_category_id`);
ALTER TABLE `T_LON_REPAYHIST_H` ADD CONSTRAINT `UQ_LON_REPAYHIST_H_TRANSFER_ID` UNIQUE (`transfer_id`);
ALTER TABLE `T_PAY_TRAN_L` ADD CONSTRAINT `UQ_PAY_TRAN_L_IDEMPOTENCY_KEY` UNIQUE (`idempotency_key`);
ALTER TABLE `T_PAY_TRAN_L` ADD CONSTRAINT `UQ_PAY_TRAN_L_ORDER_ID` UNIQUE (`order_id`);
ALTER TABLE `T_MBR_CONN_R` ADD CONSTRAINT `UQ_MBR_CONN_R_PARENT_CHILD` UNIQUE (`parent_id`, `child_id`);
ALTER TABLE `T_DPT_ENROLL_M` ADD CONSTRAINT `UQ_DPT_ENROLL_M_WALLET_ID` UNIQUE (`wallet_id`);
ALTER TABLE `T_TNY_GRADE_A` ADD CONSTRAINT `UQ_TNY_GRADE_A_NAME` UNIQUE (`grade_name`);
ALTER TABLE `T_LON_PROD_M` ADD CONSTRAINT `UQ_LON_PROD_M_NAME` UNIQUE (`name`);
ALTER TABLE `T_SVG_PROD_M` ADD CONSTRAINT `UQ_SVG_PROD_M_NAME` UNIQUE (`name`);
ALTER TABLE `T_DPT_PROD_M` ADD CONSTRAINT `UQ_DPT_PROD_M_NAME` UNIQUE (`name`);
ALTER TABLE `T_WLT_CHARGE_L` ADD CONSTRAINT `UQ_WLT_CHARGE_L_IDEMPOTENCY_KEY` UNIQUE (`idempotency_key`);
ALTER TABLE `T_WLT_CHARGE_L` ADD CONSTRAINT `UQ_WLT_CHARGE_L_ORDER_ID` UNIQUE (`order_id`);
ALTER TABLE `T_ALW_SCHEDULE_M` ADD CONSTRAINT `UQ_ALW_SCHEDULE_M_PARENT_CHILD` UNIQUE (`parent_id`, `child_id`);
ALTER TABLE `T_MBR_INFO_M` ADD CONSTRAINT `UQ_MBR_INFO_M_PHONE_NUMBER` UNIQUE (`phone_number`);
ALTER TABLE `T_MBR_INFO_M` ADD CONSTRAINT `UQ_MBR_INFO_M_EMAIL` UNIQUE (`email`);
ALTER TABLE `T_SVG_ENROLL_M` ADD CONSTRAINT `UQ_SVG_ENROLL_M_WALLET_ID` UNIQUE (`wallet_id`);
ALTER TABLE `T_SVG_PAYHIST_H` ADD CONSTRAINT `UQ_SVG_PAYHIST_H_TRANSFER_ID` UNIQUE (`transfer_id`);

-- ============================================================
-- INDEX (UNIQUE로 커버되지 않는 단순 조회용 인덱스)
-- ============================================================

CREATE INDEX `IX_PAY_METHOD_M_N01` ON `T_PAY_METHOD_M` (`parent_id`);
CREATE INDEX `IX_WLT_TRF_L_N01` ON `T_WLT_TRF_L` (`from_wallet_id`);
CREATE INDEX `IX_WLT_TRF_L_N02` ON `T_WLT_TRF_L` (`to_wallet_id`);
CREATE INDEX `IX_MCC_POLICY_M_N01` ON `T_MCC_POLICY_M` (`parent_id`);
CREATE INDEX `IX_TDP_REQ_L_N01` ON `T_TDP_REQ_L` (`parent_id`);
CREATE INDEX `IX_TDP_REQ_L_N02` ON `T_TDP_REQ_L` (`child_id`);
CREATE INDEX `IX_LON_REPAYHIST_H_N01` ON `T_LON_REPAYHIST_H` (`loan_enrollment_id`);
CREATE INDEX `IX_PAY_TRAN_L_N01` ON `T_PAY_TRAN_L` (`wallet_id`);
CREATE INDEX `IX_DPT_ENROLL_M_N01` ON `T_DPT_ENROLL_M` (`child_id`);
CREATE INDEX `IX_DPT_ENROLL_M_N02` ON `T_DPT_ENROLL_M` (`parent_id`);
CREATE INDEX `IX_WLT_BASE_M_N01` ON `T_WLT_BASE_M` (`member_id`);
CREATE INDEX `IX_WLT_HIST_H_N01` ON `T_WLT_HIST_H` (`wallet_id`);
CREATE INDEX `IX_NTF_NOTI_L_N01` ON `T_NTF_NOTI_L` (`member_id`);
CREATE INDEX `IX_WLT_CHARGE_L_N01` ON `T_WLT_CHARGE_L` (`wallet_id`);
CREATE INDEX `IX_TNY_SCOREHIST_H_N01` ON `T_TNY_SCOREHIST_H` (`child_id`);
CREATE INDEX `IX_QST_VERIFY_L_N01` ON `T_QST_VERIFY_L` (`quest_id`);
CREATE INDEX `IX_ALW_SCHEDULE_M_N01` ON `T_ALW_SCHEDULE_M` (`next_payment_date`);
CREATE INDEX `IX_LON_ENROLL_M_N01` ON `T_LON_ENROLL_M` (`parent_id`);
CREATE INDEX `IX_LON_ENROLL_M_N02` ON `T_LON_ENROLL_M` (`child_id`);
CREATE INDEX `IX_QST_BASE_M_N01` ON `T_QST_BASE_M` (`parent_id`);
CREATE INDEX `IX_QST_BASE_M_N02` ON `T_QST_BASE_M` (`child_id`);
CREATE INDEX `IX_SVG_ENROLL_M_N01` ON `T_SVG_ENROLL_M` (`child_id`);
CREATE INDEX `IX_SVG_ENROLL_M_N02` ON `T_SVG_ENROLL_M` (`parent_id`);
CREATE INDEX `IX_SVG_PAYHIST_H_N01` ON `T_SVG_PAYHIST_H` (`saving_enrollment_id`);

-- ============================================================
-- CHECK
-- ============================================================

-- payment_method
ALTER TABLE `T_PAY_METHOD_M` ADD CONSTRAINT `CK_PAY_METHOD_M_TYPE`
	CHECK (`type` IN ('CARD', 'ACCOUNT'));
ALTER TABLE `T_PAY_METHOD_M` ADD CONSTRAINT `CK_PAY_METHOD_M_STATUS`
	CHECK (`status` IN ('ACTIVE', 'INACTIVE', 'EXPIRED'));
ALTER TABLE `T_PAY_METHOD_M` ADD CONSTRAINT `CK_PAY_METHOD_M_TYPE_FIELDS`
	CHECK (
		(`type` = 'CARD' AND `card_company` IS NOT NULL AND `masked_card_number` IS NOT NULL
			AND `account_bank_name` IS NULL AND `account_number` IS NULL)
		OR
		(`type` = 'ACCOUNT' AND `account_bank_name` IS NOT NULL AND `account_number` IS NOT NULL
			AND `card_company` IS NULL AND `masked_card_number` IS NULL)
	);

-- transfer
ALTER TABLE `T_WLT_TRF_L` ADD CONSTRAINT `CK_WLT_TRF_L_AMOUNT` CHECK (`amount` > 0);
ALTER TABLE `T_WLT_TRF_L` ADD CONSTRAINT `CK_WLT_TRF_L_TYPE`
	CHECK (`type` IN ('ALLOWANCE', 'DEPOSIT', 'SAVING', 'LOAN', 'TRANSFER'));
ALTER TABLE `T_WLT_TRF_L` ADD CONSTRAINT `CK_WLT_TRF_L_STATUS`
	CHECK (`status` IN ('PENDING', 'CHARGING', 'COMPLETED', 'FAILED', 'CANCELLED'));

-- category_policy
ALTER TABLE `T_MCC_POLICY_M` ADD CONSTRAINT `CK_MCC_POLICY_M_POLICY`
	CHECK (`policy` IN ('ALLOW', 'WATCH', 'BLOCK'));

-- today_permission
ALTER TABLE `T_TDP_REQ_L` ADD CONSTRAINT `CK_TDP_REQ_L_STATUS`
	CHECK (`status` IN ('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED'));

-- loan_repayment_history
ALTER TABLE `T_LON_REPAYHIST_H` ADD CONSTRAINT `CK_LON_REPAYHIST_H_PRINCIPAL_AMOUNT`
	CHECK (`principal_amount` >= 0);
ALTER TABLE `T_LON_REPAYHIST_H` ADD CONSTRAINT `CK_LON_REPAYHIST_H_PAID_PRINCIPAL_AMOUNT`
	CHECK (`paid_principal_amount` >= 0);
ALTER TABLE `T_LON_REPAYHIST_H` ADD CONSTRAINT `CK_LON_REPAYHIST_H_INTEREST_AMOUNT`
	CHECK (`interest_amount` >= 0);
ALTER TABLE `T_LON_REPAYHIST_H` ADD CONSTRAINT `CK_LON_REPAYHIST_H_PAID_INTEREST_AMOUNT`
	CHECK (`paid_interest_amount` >= 0);
ALTER TABLE `T_LON_REPAYHIST_H` ADD CONSTRAINT `CK_LON_REPAYHIST_H_STATUS`
	CHECK (`status` IN ('PAID', 'OVERDUE', 'PARTIAL'));

-- payment
ALTER TABLE `T_PAY_TRAN_L` ADD CONSTRAINT `CK_PAY_TRAN_L_APPLIED_POLICY`
	CHECK (`applied_policy` IS NULL OR `applied_policy` IN ('ALLOW', 'WATCH', 'BLOCK'));
ALTER TABLE `T_PAY_TRAN_L` ADD CONSTRAINT `CK_PAY_TRAN_L_AMOUNT` CHECK (`amount` > 0);
ALTER TABLE `T_PAY_TRAN_L` ADD CONSTRAINT `CK_PAY_TRAN_L_STATUS`
	CHECK (`status` IN ('PENDING', 'SUCCESS', 'FAILED', 'REJECTED'));

-- merchant_category
ALTER TABLE `T_MCC_CTGR_C` ADD CONSTRAINT `CK_MCC_CTGR_C_DEFAULT_POLICY`
	CHECK (`default_policy` IN ('ALLOW', 'WATCH', 'BLOCK'));

-- connection
ALTER TABLE `T_MBR_CONN_R` ADD CONSTRAINT `CK_MBR_CONN_R_STATUS`
	CHECK (`status` IN ('ACTIVE', 'INACTIVE'));

-- deposit_enrollment
ALTER TABLE `T_DPT_ENROLL_M` ADD CONSTRAINT `CK_DPT_ENROLL_M_APPLIED_RATE`
	CHECK (`applied_rate` > 0);
ALTER TABLE `T_DPT_ENROLL_M` ADD CONSTRAINT `CK_DPT_ENROLL_M_APPLIED_EARLY_TERMINATION_RATE`
	CHECK (`applied_early_termination_rate` > 0);
ALTER TABLE `T_DPT_ENROLL_M` ADD CONSTRAINT `CK_DPT_ENROLL_M_TERM_MONTHS`
	CHECK (`term_months` IN (1, 3, 6, 12));
ALTER TABLE `T_DPT_ENROLL_M` ADD CONSTRAINT `CK_DPT_ENROLL_M_STATUS`
	CHECK (`status` IN ('PENDING', 'REJECTED', 'ACTIVE', 'MATURED', 'TERMINATED'));

-- wallet
ALTER TABLE `T_WLT_BASE_M` ADD CONSTRAINT `CK_WLT_BASE_M_BALANCE` CHECK (`balance` >= 0);
ALTER TABLE `T_WLT_BASE_M` ADD CONSTRAINT `CK_WLT_BASE_M_TYPE`
	CHECK (`type` IN ('MEMBER', 'DEPOSIT', 'SAVING'));

-- wallet_history
ALTER TABLE `T_WLT_HIST_H` ADD CONSTRAINT `CK_WLT_HIST_H_ONLY_ONE_REFERENCE`
	CHECK (
		(CASE WHEN `payment_id` IS NOT NULL THEN 1 ELSE 0 END) +
		(CASE WHEN `transfer_id` IS NOT NULL THEN 1 ELSE 0 END) +
		(CASE WHEN `charge_id` IS NOT NULL THEN 1 ELSE 0 END) = 1
	);
ALTER TABLE `T_WLT_HIST_H` ADD CONSTRAINT `CK_WLT_HIST_H_DIRECTION`
	CHECK (`direction` IN ('CREDIT', 'DEBIT'));
ALTER TABLE `T_WLT_HIST_H` ADD CONSTRAINT `CK_WLT_HIST_H_AMOUNT`
	CHECK (`amount` > 0);
ALTER TABLE `T_WLT_HIST_H` ADD CONSTRAINT `CK_WLT_HIST_H_BALANCE_AFTER`
	CHECK (`balance_after` >= 0);

-- loan
ALTER TABLE `T_LON_PROD_M` ADD CONSTRAINT `CK_LON_PROD_M_BASE_RATE` CHECK (`base_rate` > 0);
ALTER TABLE `T_LON_PROD_M` ADD CONSTRAINT `CK_LON_PROD_M_LATE_FEE_RATE` CHECK (`late_fee_rate` > 0);
ALTER TABLE `T_LON_PROD_M` ADD CONSTRAINT `CK_LON_PROD_M_REPAYMENT_TYPE`
	CHECK (`repayment_type` IN ('EQUAL_PRINCIPAL_INTEREST', 'EQUAL_PRINCIPAL', 'BULLET'));
ALTER TABLE `T_LON_PROD_M` ADD CONSTRAINT `CK_LON_PROD_M_MIN_AMOUNT` CHECK (`min_amount` > 0);
ALTER TABLE `T_LON_PROD_M` ADD CONSTRAINT `CK_LON_PROD_M_MAX_AMOUNT` CHECK (`max_amount` > 0);
ALTER TABLE `T_LON_PROD_M` ADD CONSTRAINT `CK_LON_PROD_M_MIN_TEENY_SCORE` CHECK (`min_teeny_score` >= 0);

-- saving
ALTER TABLE `T_SVG_PROD_M` ADD CONSTRAINT `CK_SVG_PROD_M_SAVINGS_TYPE`
	CHECK (`savings_type` IN ('FREE', 'FIXED'));
ALTER TABLE `T_SVG_PROD_M` ADD CONSTRAINT `CK_SVG_PROD_M_INTEREST_CALCULATION_TYPE`
	CHECK (`interest_calculation_type` IN ('SIMPLE', 'COMPOUND'));
ALTER TABLE `T_SVG_PROD_M` ADD CONSTRAINT `CK_SVG_PROD_M_RATE_1M` CHECK (`rate_1m` IS NULL OR `rate_1m` > 0);
ALTER TABLE `T_SVG_PROD_M` ADD CONSTRAINT `CK_SVG_PROD_M_RATE_3M` CHECK (`rate_3m` IS NULL OR `rate_3m` > 0);
ALTER TABLE `T_SVG_PROD_M` ADD CONSTRAINT `CK_SVG_PROD_M_RATE_6M` CHECK (`rate_6m` IS NULL OR `rate_6m` > 0);
ALTER TABLE `T_SVG_PROD_M` ADD CONSTRAINT `CK_SVG_PROD_M_RATE_12M` CHECK (`rate_12m` IS NULL OR `rate_12m` > 0);
ALTER TABLE `T_SVG_PROD_M` ADD CONSTRAINT `CK_SVG_PROD_M_EARLY_TERMINATION_RATE`
	CHECK (`early_termination_rate` IS NULL OR `early_termination_rate` > 0);
ALTER TABLE `T_SVG_PROD_M` ADD CONSTRAINT `CK_SVG_PROD_M_MIN_MONTH_AMOUNT` CHECK (`min_month_amount` > 0);
ALTER TABLE `T_SVG_PROD_M` ADD CONSTRAINT `CK_SVG_PROD_M_MAX_MONTH_AMOUNT` CHECK (`max_month_amount` > 0);
ALTER TABLE `T_SVG_PROD_M` ADD CONSTRAINT `CK_SVG_PROD_M_MIN_TEENY_SCORE` CHECK (`min_teeny_score` >= 0);

-- deposit
ALTER TABLE `T_DPT_PROD_M` ADD CONSTRAINT `CK_DPT_PROD_M_RATE_1M` CHECK (`rate_1m` IS NULL OR `rate_1m` > 0);
ALTER TABLE `T_DPT_PROD_M` ADD CONSTRAINT `CK_DPT_PROD_M_RATE_3M` CHECK (`rate_3m` IS NULL OR `rate_3m` > 0);
ALTER TABLE `T_DPT_PROD_M` ADD CONSTRAINT `CK_DPT_PROD_M_RATE_6M` CHECK (`rate_6m` IS NULL OR `rate_6m` > 0);
ALTER TABLE `T_DPT_PROD_M` ADD CONSTRAINT `CK_DPT_PROD_M_RATE_12M` CHECK (`rate_12m` IS NULL OR `rate_12m` > 0);
ALTER TABLE `T_DPT_PROD_M` ADD CONSTRAINT `CK_DPT_PROD_M_EARLY_TERMINATION_RATE`
	CHECK (`early_termination_rate` > 0);
ALTER TABLE `T_DPT_PROD_M` ADD CONSTRAINT `CK_DPT_PROD_M_MIN_AMOUNT` CHECK (`min_amount` > 0);
ALTER TABLE `T_DPT_PROD_M` ADD CONSTRAINT `CK_DPT_PROD_M_MAX_AMOUNT` CHECK (`max_amount` > 0);
ALTER TABLE `T_DPT_PROD_M` ADD CONSTRAINT `CK_DPT_PROD_M_MIN_TEENY_SCORE` CHECK (`min_teeny_score` >= 0);

-- notification
ALTER TABLE `T_NTF_NOTI_L` ADD CONSTRAINT `CK_NTF_NOTI_L_TYPE`
	CHECK (`type` IN ('QUEST', 'PAYMENT', 'FINANCE', 'ALLOWANCE', 'OVERRIDE'));
ALTER TABLE `T_NTF_NOTI_L` ADD CONSTRAINT `CK_NTF_NOTI_L_REFERENCE_TYPE`
	CHECK (`reference_type` IS NULL OR `reference_type` IN (
		'QUEST', 'TODAY_PERMISSION', 'CONNECTION', 'TRANSFER', 'PAYMENT',
		'CHARGE', 'DEPOSIT_ENROLLMENT', 'SAVING_ENROLLMENT', 'LOAN_ENROLLMENT'
	));

-- charge
ALTER TABLE `T_WLT_CHARGE_L` ADD CONSTRAINT `CK_WLT_CHARGE_L_STATUS`
	CHECK (`status` IN ('PENDING', 'SUCCESS', 'FAILED'));
ALTER TABLE `T_WLT_CHARGE_L` ADD CONSTRAINT `CK_WLT_CHARGE_L_AMOUNT`
	CHECK (`amount` > 0);  

-- teeny_score_history
ALTER TABLE `T_TNY_SCOREHIST_H` ADD CONSTRAINT `CK_TNY_SCOREHIST_H_SCORE_AFTER`
	CHECK (`score_after` BETWEEN 0 AND 1000);
ALTER TABLE `T_TNY_SCOREHIST_H` ADD CONSTRAINT `CK_TNY_SCOREHIST_H_REFERENCE_TYPE`
	CHECK (`reference_type` IS NULL OR `reference_type` IN (
		'QUEST', 'TODAY_PERMISSION', 'CONNECTION', 'TRANSFER', 'PAYMENT',
		'CHARGE', 'DEPOSIT_ENROLLMENT', 'SAVING_ENROLLMENT', 'LOAN_ENROLLMENT'
	));

-- quest_verification
ALTER TABLE `T_QST_VERIFY_L` ADD CONSTRAINT `CK_QST_VERIFY_L_STATUS`
	CHECK (`status` IN ('PENDING', 'APPROVED', 'REJECTED'));

-- allowance_schedule
ALTER TABLE `T_ALW_SCHEDULE_M` ADD CONSTRAINT `CK_ALW_SCHEDULE_M_AMOUNT`
	CHECK (`amount` > 0);
ALTER TABLE `T_ALW_SCHEDULE_M` ADD CONSTRAINT `CK_ALW_SCHEDULE_M_CYCLE_TYPE`
	CHECK (`cycle_type` IN ('WEEKLY', 'MONTHLY'));
ALTER TABLE `T_ALW_SCHEDULE_M` ADD CONSTRAINT `CK_ALW_SCHEDULE_M_PAYMENT_DAY`
	CHECK (
		(`cycle_type` = 'WEEKLY' AND `payment_day` BETWEEN 1 AND 7)
		OR
		(`cycle_type` = 'MONTHLY' AND `payment_day` BETWEEN 1 AND 28)
	);

-- loan_enrollment
ALTER TABLE `T_LON_ENROLL_M` ADD CONSTRAINT `CK_LON_ENROLL_M_PRINCIPAL_AMOUNT`
	CHECK (`principal_amount` > 0);
ALTER TABLE `T_LON_ENROLL_M` ADD CONSTRAINT `CK_LON_ENROLL_M_OUTSTANDING_PRINCIPAL`
	CHECK (`outstanding_principal` >= 0);
ALTER TABLE `T_LON_ENROLL_M` ADD CONSTRAINT `CK_LON_ENROLL_M_OVERDUE_INTEREST`
	CHECK (`overdue_interest` >= 0);
ALTER TABLE `T_LON_ENROLL_M` ADD CONSTRAINT `CK_LON_ENROLL_M_APPLIED_RATE`
	CHECK (`applied_rate` > 0);
ALTER TABLE `T_LON_ENROLL_M` ADD CONSTRAINT `CK_LON_ENROLL_M_APPLIED_LATE_FEE_RATE`
	CHECK (`applied_late_fee_rate` > 0);
ALTER TABLE `T_LON_ENROLL_M` ADD CONSTRAINT `CK_LON_ENROLL_M_PAYMENT_DAY`
	CHECK (`payment_day` BETWEEN 1 AND 28);
ALTER TABLE `T_LON_ENROLL_M` ADD CONSTRAINT `CK_LON_ENROLL_M_STATUS`
	CHECK (`status` IN ('PENDING', 'REJECTED', 'ACTIVE', 'OVERDUE', 'REPAID'));

-- quest
ALTER TABLE `T_QST_BASE_M` ADD CONSTRAINT `CK_QST_BASE_M_REWARD_AMOUNT` CHECK (`reward_amount` >= 0);
ALTER TABLE `T_QST_BASE_M` ADD CONSTRAINT `CK_QST_BASE_M_REWARD_TEENY_SCORE` CHECK (`reward_teeny_score` >= 0);
ALTER TABLE `T_QST_BASE_M` ADD CONSTRAINT `CK_QST_BASE_M_STATUS`
	CHECK (`status` IN ('AVAILABLE', 'IN_PROGRESS', 'PENDING', 'COMPLETED', 'FAILED'));

-- member
ALTER TABLE `T_MBR_INFO_M` ADD CONSTRAINT `CK_MBR_INFO_M_ROLE`
	CHECK (`role` IN ('PARENT', 'CHILD'));
ALTER TABLE `T_MBR_INFO_M` ADD CONSTRAINT `CK_MBR_INFO_M_TEENY_SCORE`
	CHECK (`teeny_score` IS NULL OR `teeny_score` BETWEEN 0 AND 1000);
ALTER TABLE `T_MBR_INFO_M` ADD CONSTRAINT `CK_MBR_INFO_M_STATUS`
	CHECK (`status` IN ('ACTIVE', 'INACTIVE'));

-- saving_enrollment
ALTER TABLE `T_SVG_ENROLL_M` ADD CONSTRAINT `CK_SVG_ENROLL_M_APPLIED_RATE`
	CHECK (`applied_rate` > 0);
ALTER TABLE `T_SVG_ENROLL_M` ADD CONSTRAINT `CK_SVG_ENROLL_M_APPLIED_EARLY_TERMINATION_RATE`
	CHECK (`applied_early_termination_rate` > 0);
ALTER TABLE `T_SVG_ENROLL_M` ADD CONSTRAINT `CK_SVG_ENROLL_M_TERM_MONTHS`
	CHECK (`term_months` IN (1, 3, 6, 12));
ALTER TABLE `T_SVG_ENROLL_M` ADD CONSTRAINT `CK_SVG_ENROLL_M_MONTHLY_AMOUNT`
	CHECK (`monthly_amount` IS NULL OR `monthly_amount` > 0);
ALTER TABLE `T_SVG_ENROLL_M` ADD CONSTRAINT `CK_SVG_ENROLL_M_PAYMENT_DAY`
	CHECK (`payment_day` IS NULL OR `payment_day` BETWEEN 1 AND 28);
ALTER TABLE `T_SVG_ENROLL_M` ADD CONSTRAINT `CK_SVG_ENROLL_M_STATUS`
	CHECK (`status` IN ('PENDING', 'REJECTED', 'ACTIVE', 'MATURED', 'TERMINATED'));

-- saving_payment_history
ALTER TABLE `T_SVG_PAYHIST_H` ADD CONSTRAINT `CK_SVG_PAYHIST_H_AMOUNT`
	CHECK (`amount` IS NULL OR `amount` > 0);
ALTER TABLE `T_SVG_PAYHIST_H` ADD CONSTRAINT `CK_SVG_PAYHIST_H_PAID_AMOUNT`
	CHECK (`paid_amount` >= 0);
ALTER TABLE `T_SVG_PAYHIST_H` ADD CONSTRAINT `CK_SVG_PAYHIST_H_STATUS`
	CHECK (`status` IN ('PAID', 'MISSED', 'PARTIAL'));

-- [보호자 가입 흐름 9] 가입 요청 버전의 유효성을 확인할 약관 원본 테이블
CREATE TABLE `T_MBR_AGRMT_M` (
                                 `id` BIGINT NOT NULL COMMENT '약관 아이디',
                                 `code` VARCHAR(50) NOT NULL COMMENT '약관 코드',
                                 `version` VARCHAR(20) NOT NULL COMMENT '약관 버전',
                                 `title` VARCHAR(100) NOT NULL COMMENT '약관 제목',
                                 `content` TEXT NOT NULL COMMENT '약관 내용',
                                 `is_required` BOOLEAN NOT NULL DEFAULT FALSE COMMENT '필수 동의 여부',
                                 `effective_at` DATETIME NOT NULL COMMENT '적용 시작 일시',
                                 `expired_at` DATETIME NULL COMMENT '적용 종료 일시',
                                 `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
                                 `updated_at` DATETIME NULL COMMENT '수정 일시'
);

-- [보호자 가입 흐름 14] 회원별 약관 동의 주체와 인증 근거 이력
CREATE TABLE `T_MBR_AGRMT_H` (
                                 `id` BIGINT NOT NULL COMMENT '회원 약관 동의 이력 아이디',
                                 `member_id` BIGINT NOT NULL COMMENT '동의 대상 회원 아이디',
                                 `agreement_id` BIGINT NOT NULL COMMENT '약관 아이디',
                                 `status` VARCHAR(20) NOT NULL COMMENT '동의 상태: AGREED/WITHDRAWN',
                                 `actor_type` VARCHAR(20) NOT NULL COMMENT '동의 수행자: SELF/LEGAL_GUARDIAN',
                                 `actor_member_id` BIGINT NULL COMMENT '동의 수행 회원 아이디',
                                 `verification_method` VARCHAR(20) NULL COMMENT '법정대리인 확인 방법: SMS/PASS 등',
                                 `verification_reference` VARCHAR(100) NULL COMMENT '본인확인 요청 식별값',
                                 `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '동의 또는 철회 일시'
);

ALTER TABLE `T_MBR_AGRMT_M`
    MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT,
    ADD CONSTRAINT `PK_MBR_AGRMT_M` PRIMARY KEY (`id`),
    ADD CONSTRAINT `UQ_MBR_AGRMT_M_CODE_VERSION`
        UNIQUE (`code`, `version`);

ALTER TABLE `T_MBR_AGRMT_H`
    MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT,
    ADD CONSTRAINT `PK_MBR_AGRMT_H` PRIMARY KEY (`id`);

ALTER TABLE `T_MBR_AGRMT_H`
    ADD CONSTRAINT `FK_T_MBR_INFO_M_TO_T_MBR_AGRMT_H_1`
        FOREIGN KEY (`member_id`)
            REFERENCES `T_MBR_INFO_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_MBR_AGRMT_H`
    ADD CONSTRAINT `FK_T_MBR_AGRMT_M_TO_T_MBR_AGRMT_H_1`
        FOREIGN KEY (`agreement_id`)
            REFERENCES `T_MBR_AGRMT_M` (`id`) ON DELETE RESTRICT;

ALTER TABLE `T_MBR_AGRMT_H`
    ADD CONSTRAINT `FK_T_MBR_INFO_M_TO_T_MBR_AGRMT_H_2`
        FOREIGN KEY (`actor_member_id`)
            REFERENCES `T_MBR_INFO_M` (`id`) ON DELETE RESTRICT;

CREATE INDEX `IX_MBR_AGRMT_H_N01`
    ON `T_MBR_AGRMT_H` (`member_id`, `agreement_id`, `created_at`);

ALTER TABLE `T_MBR_AGRMT_H`
    ADD CONSTRAINT `CK_MBR_AGRMT_H_STATUS`
        CHECK (`status` IN ('AGREED', 'WITHDRAWN'));

ALTER TABLE `T_MBR_AGRMT_H`
    ADD CONSTRAINT `CK_MBR_AGRMT_H_ACTOR_TYPE`
        CHECK (`actor_type` IN ('SELF', 'LEGAL_GUARDIAN'));

-- [보호자 가입 흐름 13] 비회원 법정대리인 인증 정보를 자녀 회원과 연결
CREATE TABLE `T_MBR_LEGAL_GUARDIAN_M` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '비회원 법정대리인 정보 아이디',
    `child_member_id` BIGINT NOT NULL COMMENT '동의 대상 자녀 회원 아이디',
    `name` VARCHAR(50) NOT NULL COMMENT '법정대리인 이름',
    `phone_number` VARCHAR(20) NOT NULL COMMENT '인증한 휴대폰 번호',
    `relationship` VARCHAR(30) NOT NULL COMMENT '관계: FATHER/MOTHER/OTHER_LEGAL_GUARDIAN',
    `verification_method` VARCHAR(20) NOT NULL COMMENT '확인 방법: SMS_TEST/PASS 등',
    `verification_reference` VARCHAR(100) NOT NULL COMMENT '인증 요청 식별값',
    `verified_at` DATETIME NOT NULL COMMENT '인증 완료 일시',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    CONSTRAINT `PK_MBR_LEGAL_GUARDIAN_M` PRIMARY KEY (`id`),
    CONSTRAINT `UQ_MBR_LEGAL_GUARDIAN_M_VERIFICATION_REFERENCE`
        UNIQUE (`verification_reference`),
    CONSTRAINT `FK_T_MBR_INFO_M_TO_T_MBR_LEGAL_GUARDIAN_M_1`
        FOREIGN KEY (`child_member_id`) REFERENCES `T_MBR_INFO_M` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `CK_MBR_LEGAL_GUARDIAN_M_RELATIONSHIP`
        CHECK (`relationship` IN ('FATHER', 'MOTHER', 'OTHER_LEGAL_GUARDIAN'))
);

CREATE INDEX `IX_MBR_LEGAL_GUARDIAN_M_N01`
    ON `T_MBR_LEGAL_GUARDIAN_M` (`child_member_id`);
